servers:
  local_staging:
    url: http://localhost:18080
  local_prod:
    url: http://localhost:18081
  emr_staging:
    emr_cluster_arn: "arn:aws:elasticmapreduce:us-east-1:812883729761:cluster/j-2QA06H5A86CY7"
    aws_profile: staging
    timeout: 30
  emr_prod:
    emr_cluster_arn: "arn:aws:elasticmapreduce:us-east-1:348517286947:cluster/j-2MOIBIP6NHJQI"
    aws_profile: prod
    timeout: 30
mcp:
  transports:
  - stdio
  port: '18888'
  debug: true
  address: localhost
